version: '3'

services:
  frontend:
    build:
      context: ./FrontDeploy
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    env_file:
      - ./FrontDeploy/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./Deploy
      dockerfile: Dockerfile
    ports:
      - "80:9000"
    env_file:
      - ./Deploy/.env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
