# name: Deploy to VPS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username:

#       - name: Build and push Docker image
#         run: |
#           docker build -t your-dockerhub-username/mern-frontend:latest -f frontend/Dockerfile frontend
#           docker build -t your-dockerhub-username/mern-backend:latest -f backend/Dockerfile backend
#           docker push your-dockerhub-username/mern-frontend:latest
#           docker push your-dockerhub-username/mern-backend:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - name: Deploy to VPS
#         uses: appleboy/ssh-action@master
#         with:
#           host:
#             docker pull your-dockerhub-username/mern-frontend:latest
#             docker pull your-dockerhub-username/mern-backend:latest
#             docker-compose down
#             docker-compose up -d


name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/mern-frontend:latest -f FrontDeploy/Dockerfile FrontDeploy
          docker build -t your-dockerhub-username/mern-backend:latest -f Deploy/Dockerfile Deploy
          docker push your-dockerhub-username/mern-frontend:latest
          docker push your-dockerhub-username/mern-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            docker pull your-dockerhub-username/mern-frontend:latest
            docker pull your-dockerhub-username/mern-backend:latest
            cd /path/to/your/docker-compose/directory
            docker-compose down
            docker-compose up -d
