name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      
      - name: Debug Git info
        run: |
           git status
           git submodule status
           git config --list

      - name: Debug repository structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Repository root contents:"
          ls -la
          echo "FrontDeploy folder contents:"
          ls -la FrontDeploy || echo "FrontDeploy not found"
          echo "Deploy folder contents:"
          ls -la Deploy || echo "Deploy not found"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          if [ -d "./FrontDeploy" ] && [ -f "./FrontDeploy/Dockerfile" ]; then
            echo "Building frontend Docker image"
            docker build -t sokhi/mern-frontend:latest ./FrontDeploy
            docker push sokhi/mern-frontend:latest
          else
            echo "Frontend Dockerfile not found"
            exit 1
          fi

          if [ -d "./Deploy" ] && [ -f "./Deploy/Dockerfile" ]; then
            echo "Building backend Docker image"
            docker build -t sokhi/mern-backend:latest ./Deploy
            docker push sokhi/mern-backend:latest
          else
            echo "Backend Dockerfile not found"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/root/"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/root/
            docker pull sokhi/mern-frontend:latest
            docker pull sokhi/mern-backend:latest
            docker-compose down
            docker-compose up -d