name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      - name: List repository contents
        run: |
          pwd
          ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          ls FrontDeploy  # Verify directory contents
          ls Deploy       # Verify directory contents
          cd FrontDeploy
          docker build -t sokhi/mern-frontend:latest -f Dockerfile .
          cd ../Deploy
          docker build -t sokhi/mern-backend:latest -f Dockerfile .
          docker push sokhi/mern-frontend:latest
          docker push sokhi/mern-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/root/"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/root/
            docker pull sokhi/mern-frontend:latest
            docker pull sokhi/mern-backend:latest
            docker-compose down
            docker-compose up -d
